module.exports = {
    content: ["./pages/**/*.{js,ts,jsx,tsx}", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                black: "var(--black)",
                primary: {
                    DEFAULT: "var(--primary)",
                    50: "var(--primary-50)",
                    100: "var(--primary-100)",
                    200: "var(--primary-200)",
                    300: "var(--primary-300)",
                    400: "var(--primary-400)",
                    500: "var(--primary)",
                    600: "var(--primary-600)",
                    700: "var(--primary-700)",
                    800: "var(--primary-800)",
                    900: "var(--primary-900)",
                },
                secondary: {
                    DEFAULT: "var(--secondary)",
                    50: "var(--secondary-50)",
                    100: "var(--secondary-100)",
                    200: "var(--secondary-200)",
                    300: "var(--secondary-300)",
                    400: "var(--secondary-400)",
                    500: "var(--secondary)",
                    600: "var(--secondary-600)",
                    700: "var(--secondary-700)",
                    800: "var(--secondary-800)",
                    900: "var(--secondary-900)",
                },
                green: "var(--green)",
                red: "var(--red)",
                yellow: "var(--yellow)",
                grey: {
                    100: "var(--grey-1)",
                    200: "var(--grey-2)",
                    300: "var(--grey-3)",
                    400: "var(--grey-4)",
                    500: "var(--grey-5)",
                },
            },
        },
        fontFamily: {
            default: ["var(--font-default)"],
            headline: ["var(--font-headline)"],
            mono: ["var(--font-mono)"],
        },
        screens: {
            sm: "600px",
            md: "1000px",
        },
    },
    plugins: [],
};
